# 1주차 선형대수 응용
numpy를 통한 행렬계산

In [1]:
import numpy as np

In [9]:
x=np.array([5,6])
x+x

array([10, 12])

In [10]:
A=np.array([[1,2],[3,4]])
A+x

array([[ 6,  8],
       [ 8, 10]])

ㄴ각각에 대해 더한다.

In [11]:
# 예시)


SyntaxError: unmatched ')' (<ipython-input-11-e1d279994ce3>, line 1)

In [29]:
x=np.array([1,2])
A=np.array([[2,2],
            [2,2]])


In [30]:
np.dot(x,A)

array([6, 6])

In [31]:
np.dot(A,x)

array([6, 6])

In [17]:
A*x

array([[2, 4],
       [2, 4]])

In [20]:
np.dot(A,x)

array([6, 6])

In [21]:
np.dot(x,A)

array([6, 6])

ㄴ내적, Dot product

In [23]:
A=np.array([[1,2],  
            [3,4]])
B=np.array([[5,6],
            [7,8]])

In [24]:
np.dot(B,A)

array([[23, 34],
       [31, 46]])

In [25]:
np.dot(A,B)
# [1*5+2*7,1*6+2*8],
# [3*5+4*7,3*6+4*8]

# [A11*B11+A12*B21,A11*B11+A12*B21],
# [A21*B11+A22*B21,A21*B12+A22*B22]



array([[19, 22],
       [43, 50]])

A11 A12
A21 A22

B11 B12
B21 B22

In [33]:
A=np.array([[2,4],
            [6,8]])
x=np.array([1,2])

In [35]:
print(A*x)
print(np.dot(A,x))

[[ 2  8]
 [ 6 16]]
[10 22]


ㄴ
(2 4)(1)//
(6 8)(2)

연립방정식

Ax=b
A:주어진 정보
b:조건
x:변수행렬

x: np.linalg.solve(A,b)

In [38]:
# 토끼와 닭
A=np.array([[1,1],
            [4,2]])
b=np.array([[36],
            [92]])
np.linalg.solve(A,b)

array([[10.],
       [26.]])

In [128]:
# 양 100마리
# 10000000원
# 수 200000
# 암 100000
# 새끼 100000/3

# A=np.array([[1,1,ㅁ],
#             [4,2,ㅁ]],
#             [ㅁ,ㅁ,ㅁ])
# b=np.array([[36],
#             [92],
#             [ㅁ]])
# np.linalg.solve(A,b)

# result=np.array([])
# for i in range(1,300+1):
# #     print(i)
#     if i%3==0:
#         A=np.array([[200000,100000,100000/3],
#                     [1,1,1],
#                     [0,0,1]])
#         b=np.array([[10000000,
#                      100,
#                      i]]).T
#         x=np.linalg.solve(A,b)
#         print(x)
# #         if type[x[0]]==int:

i=0
x=np.array([1,1,1])
while x[0]*x[1]*x[2]!=0: 
    i+=1
#     print(i)
    if i%3==0:
        A=np.array([[200000,100000,100000/3],
                    [1,1,1],
                    [0,0,1]])
        b=np.array([[10000000,
                     100,
                     i]]).T
        x=np.linalg.solve(A,b)
#         print(x)
        
        if x[0]*x[1]*x[2]!=0:
            result=np.append(result,x[2])
result

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30., 33., 36., 39.,
       42., 45., 48., 51., 54., 57.,  3.,  6.,  9., 12., 15., 18., 21.,
       24., 27., 30., 33., 36., 39., 42., 45., 48., 51., 54., 57.,  3.,
        6.,  9., 12., 15., 18., 21., 24., 27., 30., 33., 36., 39., 42.,
       45., 48., 51., 54., 57.,  3.,  6.,  9., 12., 15., 18., 21., 24.,
       27., 30., 33., 36., 39., 42., 45., 48., 51., 54., 57.,  3.,  6.,
        9., 12., 15., 18., 21., 24., 27., 30., 33., 36., 39., 42., 45.,
       48., 51., 54., 57.])

In [86]:
print(x[0]>0&x[1]>0&x[2]>0)

False


In [94]:
x[0]>=1 


array([ True])

In [111]:
i=1
while i !=10:
    print(i)
    i +=1

1
2
3
4
5
6
7
8
9
